sequinsbio/sequintools

.github/workflows/build-and-push-docker-image.yml
We'll use ghcr.io to release our docker images,
so there's no need to push them to azurecr
anymore.
Fixes: #103
=> ci: stop pushing docker images to azurecr

release-please-config.json
By default release-please wants to tag the release
with the component name. This is not necessary for
sequintools as this is a monorepo with only one
project in it.
This was also breaking our automation for creating
the docker sematic version tags.
Part of #106
=> fix: do not include component in the release tag

release-please-config.json
There was a typo 'reqest' in the config.
We only do single releases from this repo, so this
config was not taking effect anyway. Use
`pull-request-title-pattern` instead.
Part of #106
=> ci: fix typo in release config

Dockerfile
Nextflow needs the `ps` command from `procps`.
Fixes: #129
=> Allow the docker image to be used by nextflow

.github/dependabot.yml
Add dependabot config to check our Dockerfile
dependencies once a week.
Fixes: #131
=> chore: dependabot config for Dockerfile

.github/dependabot.yml
Fix the prefix used by dependabot in commit
messages so that the style matches conventional
commits.
Even though gitlint is now configured to ignore
dependabot commits, this will still look better in the commit log.
=> chore: fix dependabot commit messages

release-please-config.json
release-please has special configuration options
when the current version is < 1.0.0.
These options are controlled with the flags
`bump-minor-pre-major` and
`bump-patch-for-minor-pre-major`. In this case,
setting `bump-patch-for-minor-pre-major` to false
will ensure that any new features will bump the
minor version even if the current release is
< 1.0.0.
=> ci: bump minor version for a new feat

.github/workflows/build-and-push-docker-image.yml
When we create a new release, the workflow is
triggered twice, once for the new tag and once
for the CL landing on main.
Use concurrency group to ensure that only one
docker build runs at a time, and hopefully the
second run will use cached artifacts.
Fixes #142
=> ci: configure concurrency group for docker builds

src/calibrate.rs, src/main.rs
If a user passes `--bedcov-max-depth 0` to the `bedcov` subcommand, it
is now interpreted as no limit on the maximum depth of coverage. This
mimics how the `--max-depth` option for `samtools mpileup` works.
=> feat: interpret bedcov max depth 0 as no limit

Cargo.lock, Cargo.toml, src/calibrate.rs
Dependabot raised PRs to update rand_pcg and rand,
but as seperate PRs. This seems to cause a build
error, so I'm combining them into one PR.
Also, fixed a depreciation warning in calibrate.rs
related to the uprev.
=> fix: uprev random dependencies

.github/workflows/release-please.yml
We have an organizational secret for the
sequins-bot access token that we should use
instead of the repository specific token.
=> ci: use the organization secret for sequins-bot

.github/workflows/release-please.yml
We don't need to run release-please on every
commit. We can run it weekly instead and
establish a weekly release cadence.
Run it on Wednesdays at 06:00 Sydney time so we
can review and release on Wednesdays.
=> ci: change release-please to run weekly

src/calibrate.rs
When calibrating to a standard coverage, the mean coverage was
consistently higher than expected. This was due to an error in the way
reads were selected for keeping or excluding resulting is some
singletons being mistakenly retained. This commit fixes this so that
both pairs of a fragment are always retained, and the resulting mean
coverage is closer to the requested coverage.
=> feat: adjust calibration algorithm for standard coverage

.devcontainer/postCreateCommand.sh, .github/workflows/release-please.yml
When the release please config or manifest
changes, we need to run release please to
actually create the release.
=> chore: run release please on config change

.github/workflows/build-and-push-docker-image.yml
Outdated tools that only support the legacy GitHub Cache service API v1.
Use suggested workaround to fix it.
#183
=> fix: legacy cache api

.github/workflows/build-and-push-docker-image.yml
Update docker build workflow to use the current
latest version of buildx.
=> chore: latest version of buildx is v0.23.0

.devcontainer/Dockerfile, .github/workflows/test-and-lint-without-devcontainer.yml
This updates the devcontainer to use a more precisely pinned version of
the container, which also pins the Rust version, and updates the action
that runs outside of the devcontainer to use the same Rust version.
`actions-rs/toolchain` is replaced by `dtolnay/rust-toolchain` as the
former is archived and unmaintained, while the latter is under active
maintanance.
Closes #195
=> ci: same rust version in devcontainer and workflows

src/bedcov.rs, src/calibrate.rs, src/region.rs
Sets the thread count to the number of available CPUs when reading BAM
files. Depending on the number of CPUs available, this can significantly
improve the run time of the calibrated and bedcov commands.
=> feat: use multi threads when reading bams

Cargo.toml
crates.io has a size limit of 10MB per crate. The example directory is
almost 10MB by itself. This commit updates Cargo.toml to exclude the
example directory from the crate so it can successfully be uploaded to
crates.io.
=> fix: reduce crate size to complie with crates.io restrictions

src/calibrate.rs, src/main.rs
This adds support for CRAM output with the `-C`, `--cram` arguments.
Closes #199
=> feat: add support for CRAM output

.github/workflows/build-binaries.yml
This adds a GitHub Action to build binaries for multiple architectures
and upload them as assets to each release. Currently, the arch are:
x86_64-unknown-linux-musl
aarch64-apple-darwin
This provides another way people can obtain the software.
=> ci: build and upload binaries on release

.github/workflows/build-binaries.yml
When attempting to build for the target `x86_64-unknown-linux-musl` on
ubuntu, we need to also install some extra musl build dependencies.
=> fix(ci): add musl dependencies to build

deny.toml
Add OSI-approved Unicode-3.0 to the list of accepted licenses in
`deny.toml`. This is needed as a recent update to rust-htslib is pulling
in multiple dependencies that use this license.
=> chore: update allowed licenses

Cargo.toml, deny.toml
This advisory was being ignored while waiting for rust-htslib to update
dependencies. rust-htslib has merged the PR with this fix, so ignoring
the advisory is no longer necessary.
Closes #70
=> chore: remove RUSTSEC-2024-0421 advisory check

src/bedcov.rs, src/calibrate.rs, src/main.rs
The `bedcov` command accepts an optional list of thresholds. For each
threshold a column is added to the output to indicate the percentage of
bases in each reported region that have a coverage greater that the
threshold.
=> feat: add coverage uniformity stats to bedcov output

.github/workflows/build-binaries.yml
When building release binaries, add the rust musl target on Linux.
=> ci: add musl target when building binaries

.dockerignore, Dockerfile
It's useful to have a copy of `samtools` in the `sequintools` container
as it can be used to manipulate the output BAM file in many ways.
=> feat: add samtools to docker container

Cargo.lock, Cargo.toml, src/bedcov.rs, src/calibrate.rs, src/errors.rs, src/lib.rs, src/main.rs, src/region.rs
This commit creates a library crate along side the main binary crate.
Within the library, proper error types are used and the use of `anyhow`
is eliminated. The `region` module has been placed inside the new
library.
This is the first stage of a multi-stage refactoring with the aim to
improve the code structure to improve our ability to test code and allow
the introduction of a much faster coverage calculation algorithm.
=> refactor: create a library that the binary depends on

Cargo.lock, Cargo.toml, src/bam.rs, src/coverage.rs, src/lib.rs, src/main.rs, src/region.rs, testdata/calibrated.bed
This module adds a new algorithm for calculating coverage of a BAM file
and high level functions to create CSV data from coverage. It adds the
`rayon` crate to enable parallel processing of BED regions when
calculating coverage. On a high depth sample sequins BAM (>100,000X
coverage) the run time goes from ~15-20m to <20s.
Subsequent commits will update the commands of the main program to use
these newer - more performant - coverage calculation algorithms.
=> feat: add library coverage module

src/coverage.rs
This commit fixes a bug that caused `bedcov` to exit with an error when
a region from the input BED file had no coverage. It now correctly
reports the stats as 0 for everything.
=> fix: bedcov does not error when missing coverage

.github/workflows/test-and-lint-without-devcontainer.yml
This commit changes the GitHub Action that builds test coverage reports from using tarpaulin to llvm-cov. tarpaulin can produce many false positives (in terms of lines uncovered by tests), which in turn can cause patch coverage to be very deceptive. llvm-cov is reported as being more accurate and faster; all current advice seems to point to using llvm-cov over tarpaulin.
=> ci: update from tarpaulin to llvm-cov for test coverage

src/calibration.rs, src/coverage.rs, src/errors.rs, src/lib.rs
The `calibration` module contains a new implementation of the calibration code that uses the `BamReader` and `BamWriter` traits rather than directly using the `rust_htslib` types. This improves the flexibility of the library functions, and makes testing easier.
Future commits will update the `calibrate` command to use these new library functions.
=> feat: add calibration module

.dockerignore, build.rs
A previous commit updated the way the version is detected in a way that requires the git directory (`.git`). This was not being sent to the docker daemon when building containers causing a failure. This commit removes the git directory from the `.dockerignore` file and makes the build function more robust when `.git` is missing.
=> ci: remove .git from .dockerignore
